AWSTemplateFormatVersion: '2010-09-09'

Description: S3 CICD Backup

Parameters:
# ------------------------------------------------------------#
# Parameters
# ------------------------------------------------------------# 
  BucketNameBackup:
    Type: String
    Default: s3-cicd-backup
  BucketNameProd:
    Type: String
    Default: s3-cicd-prod

  

# ------------------------------------------------------------#
# S3　backup
# ------------------------------------------------------------# 
Resources:
  s3bucketbackup:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketName: !Sub ${BucketNameBackup}-${AWS::AccountId}
      PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
      VersioningConfiguration: 
        Status: Suspended
      BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
              BucketKeyEnabled: true
      Tags:
        - Key: Name
          Value: !Sub ${BucketNameBackup}-${AWS::AccountId}

  s3BucketPolicyBackup:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref s3bucketbackup
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Action:
            - "s3:GetObject"
            Effect: Allow
            Resource: !Sub "arn:${AWS::Partition}:s3:::${BucketNameBackup}-${AWS::AccountId}/*"
            Principal: 
              AWS: !Sub arn:aws:iam::674078804300:user/Administrator
# ------------------------------------------------------------#
# S3 prod
# ------------------------------------------------------------#
  s3bucketprod:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketName: !Sub ${BucketNameProd}-${AWS::AccountId}
      PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
      VersioningConfiguration: 
        Status: Suspended
      BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
              BucketKeyEnabled: true
      Tags:
        - Key: Name
          Value: !Sub ${BucketNameProd}-${AWS::AccountId}

  s3BucketPolicyProd:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref s3bucketprod
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Action:
            - "s3:GetObject"
            Effect: Allow
            Resource: !Sub "arn:${AWS::Partition}:s3:::${BucketNameProd}-${AWS::AccountId}/*"
            Principal: 
              AWS: !Sub arn:aws:iam::674078804300:user/Administrator

Outputs:
  s3bucketbackup:
    Value: !Ref s3bucketbackup
    Export: 
      Name: s3bucketbackup

  s3BucketPolicyProd:
    Value: !Ref s3bucketprod
    Export:
      Name: s3bucketprod
    

